# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenericTelemetryDialog.ui'
#
# Created: Thu Jun 25 09:52:44 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)

class Ui_GenericTelemetryDialog(object):
    def setupUi(self, GenericTelemetryDialog):
        GenericTelemetryDialog.setObjectName("GenericTelemetryDialog")
        GenericTelemetryDialog.setWindowModality(QtCore.Qt.NonModal)
        GenericTelemetryDialog.resize(750, 434)
        font = QtGui.QFont()
        font.setPointSize(13)
        GenericTelemetryDialog.setFont(font)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(GenericTelemetryDialog)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.subSystemTelemetryPageLabel = QtWidgets.QLabel(GenericTelemetryDialog)
        self.subSystemTelemetryPageLabel.setObjectName("subSystemTelemetryPageLabel")
        self.verticalLayout.addWidget(self.subSystemTelemetryPageLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.subSystemTextBrowser = QtWidgets.QTextBrowser(GenericTelemetryDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subSystemTextBrowser.sizePolicy().hasHeightForWidth())
        self.subSystemTextBrowser.setSizePolicy(sizePolicy)
        self.subSystemTextBrowser.setMinimumSize(QtCore.QSize(141, 31))
        self.subSystemTextBrowser.setMaximumSize(QtCore.QSize(141, 31))
        self.subSystemTextBrowser.setObjectName("subSystemTextBrowser")
        self.horizontalLayout.addWidget(self.subSystemTextBrowser)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.packetIdLabel = QtWidgets.QLabel(GenericTelemetryDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.packetIdLabel.sizePolicy().hasHeightForWidth())
        self.packetIdLabel.setSizePolicy(sizePolicy)
        self.packetIdLabel.setMinimumSize(QtCore.QSize(0, 13))
        self.packetIdLabel.setMaximumSize(QtCore.QSize(16777215, 13))
        self.packetIdLabel.setObjectName("packetIdLabel")
        self.verticalLayout_2.addWidget(self.packetIdLabel)
        self.packetId = QtWidgets.QLCDNumber(GenericTelemetryDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.packetId.sizePolicy().hasHeightForWidth())
        self.packetId.setSizePolicy(sizePolicy)
        self.packetId.setObjectName("packetId")
        self.verticalLayout_2.addWidget(self.packetId)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(GenericTelemetryDialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.sequenceCount = QtWidgets.QTextBrowser(GenericTelemetryDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequenceCount.sizePolicy().hasHeightForWidth())
        self.sequenceCount.setSizePolicy(sizePolicy)
        self.sequenceCount.setMinimumSize(QtCore.QSize(101, 31))
        self.sequenceCount.setMaximumSize(QtCore.QSize(101, 31))
        self.sequenceCount.setObjectName("sequenceCount")
        self.verticalLayout_3.addWidget(self.sequenceCount)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(146, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(GenericTelemetryDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(GenericTelemetryDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(161, 17))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(GenericTelemetryDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(151, 0))
        self.label_2.setMaximumSize(QtCore.QSize(151, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.line_2 = QtWidgets.QFrame(GenericTelemetryDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.label_4 = QtWidgets.QLabel(GenericTelemetryDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(161, 17))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(GenericTelemetryDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(151, 0))
        self.label_3.setMaximumSize(QtCore.QSize(151, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.scrollArea = QtWidgets.QScrollArea(GenericTelemetryDialog)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 709, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.itemLabelTextBrowser_1 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_1.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_1.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_1.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_1.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_1.setObjectName("itemLabelTextBrowser_1")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_1)
        self.itemLabelTextBrowser_2 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_2.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_2.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_2.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_2.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_2.setObjectName("itemLabelTextBrowser_2")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_2)
        self.itemLabelTextBrowser_3 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_3.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_3.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_3.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_3.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_3.setObjectName("itemLabelTextBrowser_3")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_3)
        self.itemLabelTextBrowser_4 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_4.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_4.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_4.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_4.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_4.setObjectName("itemLabelTextBrowser_4")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_4)
        self.itemLabelTextBrowser_5 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_5.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_5.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_5.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_5.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_5.setObjectName("itemLabelTextBrowser_5")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_5)
        self.itemLabelTextBrowser_6 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_6.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_6.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_6.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_6.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_6.setObjectName("itemLabelTextBrowser_6")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_6)
        self.itemLabelTextBrowser_7 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_7.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_7.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_7.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_7.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_7.setObjectName("itemLabelTextBrowser_7")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_7)
        self.itemLabelTextBrowser_8 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_8.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_8.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_8.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_8.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_8.setObjectName("itemLabelTextBrowser_8")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_8)
        self.itemLabelTextBrowser_9 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_9.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_9.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_9.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_9.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_9.setObjectName("itemLabelTextBrowser_9")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_9)
        self.itemLabelTextBrowser_10 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_10.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_10.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_10.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_10.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_10.setObjectName("itemLabelTextBrowser_10")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_10)
        self.itemLabelTextBrowser_11 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_11.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_11.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_11.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_11.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_11.setObjectName("itemLabelTextBrowser_11")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_11)
        self.itemLabelTextBrowser_12 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_12.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_12.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_12.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_12.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_12.setObjectName("itemLabelTextBrowser_12")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_12)
        self.itemLabelTextBrowser_13 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_13.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_13.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_13.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_13.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_13.setObjectName("itemLabelTextBrowser_13")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_13)
        self.itemLabelTextBrowser_14 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_14.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_14.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_14.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_14.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_14.setObjectName("itemLabelTextBrowser_14")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_14)
        self.itemLabelTextBrowser_15 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_15.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_15.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_15.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_15.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_15.setObjectName("itemLabelTextBrowser_15")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_15)
        self.itemLabelTextBrowser_16 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_16.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_16.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_16.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_16.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_16.setObjectName("itemLabelTextBrowser_16")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_16)
        self.itemLabelTextBrowser_17 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_17.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_17.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_17.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_17.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_17.setObjectName("itemLabelTextBrowser_17")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_17)
        self.itemLabelTextBrowser_18 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_18.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_18.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_18.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_18.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_18.setObjectName("itemLabelTextBrowser_18")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_18)
        self.itemLabelTextBrowser_19 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_19.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_19.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_19.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_19.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_19.setObjectName("itemLabelTextBrowser_19")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_19)
        self.itemLabelTextBrowser_20 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_20.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_20.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_20.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_20.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_20.setObjectName("itemLabelTextBrowser_20")
        self.verticalLayout_4.addWidget(self.itemLabelTextBrowser_20)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.itemValueTextBrowser_1 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_1.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_1.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_1.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_1.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_1.setObjectName("itemValueTextBrowser_1")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_1)
        self.itemValueTextBrowser_2 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_2.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_2.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_2.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_2.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_2.setObjectName("itemValueTextBrowser_2")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_2)
        self.itemValueTextBrowser_3 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_3.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_3.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_3.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_3.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_3.setObjectName("itemValueTextBrowser_3")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_3)
        self.itemValueTextBrowser_4 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_4.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_4.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_4.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_4.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_4.setObjectName("itemValueTextBrowser_4")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_4)
        self.itemValueTextBrowser_5 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_5.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_5.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_5.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_5.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_5.setObjectName("itemValueTextBrowser_5")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_5)
        self.itemValueTextBrowser_6 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_6.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_6.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_6.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_6.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_6.setObjectName("itemValueTextBrowser_6")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_6)
        self.itemValueTextBrowser_7 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_7.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_7.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_7.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_7.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_7.setObjectName("itemValueTextBrowser_7")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_7)
        self.itemValueTextBrowser_8 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_8.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_8.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_8.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_8.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_8.setObjectName("itemValueTextBrowser_8")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_8)
        self.itemValueTextBrowser_9 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_9.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_9.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_9.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_9.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_9.setObjectName("itemValueTextBrowser_9")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_9)
        self.itemValueTextBrowser_10 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_10.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_10.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_10.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_10.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_10.setObjectName("itemValueTextBrowser_10")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_10)
        self.itemValueTextBrowser_11 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_11.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_11.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_11.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_11.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_11.setObjectName("itemValueTextBrowser_11")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_11)
        self.itemValueTextBrowser_12 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_12.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_12.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_12.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_12.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_12.setObjectName("itemValueTextBrowser_12")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_12)
        self.itemValueTextBrowser_13 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_13.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_13.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_13.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_13.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_13.setObjectName("itemValueTextBrowser_13")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_13)
        self.itemValueTextBrowser_14 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_14.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_14.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_14.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_14.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_14.setObjectName("itemValueTextBrowser_14")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_14)
        self.itemValueTextBrowser_15 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_15.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_15.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_15.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_15.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_15.setObjectName("itemValueTextBrowser_15")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_15)
        self.itemValueTextBrowser_16 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_16.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_16.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_16.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_16.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_16.setObjectName("itemValueTextBrowser_16")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_16)
        self.itemValueTextBrowser_17 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_17.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_17.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_17.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_17.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_17.setObjectName("itemValueTextBrowser_17")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_17)
        self.itemValueTextBrowser_18 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_18.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_18.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_18.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_18.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_18.setObjectName("itemValueTextBrowser_18")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_18)
        self.itemValueTextBrowser_19 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_19.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_19.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_19.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_19.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_19.setObjectName("itemValueTextBrowser_19")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_19)
        self.itemValueTextBrowser_20 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_20.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_20.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_20.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_20.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_20.setObjectName("itemValueTextBrowser_20")
        self.verticalLayout_5.addWidget(self.itemValueTextBrowser_20)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.itemLabelTextBrowser_21 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_21.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_21.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_21.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_21.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_21.setObjectName("itemLabelTextBrowser_21")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_21)
        self.itemLabelTextBrowser_22 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_22.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_22.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_22.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_22.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_22.setObjectName("itemLabelTextBrowser_22")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_22)
        self.itemLabelTextBrowser_23 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_23.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_23.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_23.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_23.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_23.setObjectName("itemLabelTextBrowser_23")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_23)
        self.itemLabelTextBrowser_24 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_24.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_24.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_24.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_24.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_24.setObjectName("itemLabelTextBrowser_24")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_24)
        self.itemLabelTextBrowser_25 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_25.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_25.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_25.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_25.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_25.setObjectName("itemLabelTextBrowser_25")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_25)
        self.itemLabelTextBrowser_26 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_26.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_26.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_26.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_26.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_26.setObjectName("itemLabelTextBrowser_26")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_26)
        self.itemLabelTextBrowser_27 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_27.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_27.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_27.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_27.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_27.setObjectName("itemLabelTextBrowser_27")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_27)
        self.itemLabelTextBrowser_28 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_28.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_28.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_28.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_28.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_28.setObjectName("itemLabelTextBrowser_28")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_28)
        self.itemLabelTextBrowser_29 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_29.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_29.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_29.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_29.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_29.setObjectName("itemLabelTextBrowser_29")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_29)
        self.itemLabelTextBrowser_30 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_30.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_30.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_30.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_30.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_30.setObjectName("itemLabelTextBrowser_30")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_30)
        self.itemLabelTextBrowser_31 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_31.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_31.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_31.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_31.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_31.setObjectName("itemLabelTextBrowser_31")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_31)
        self.itemLabelTextBrowser_32 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_32.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_32.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_32.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_32.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_32.setObjectName("itemLabelTextBrowser_32")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_32)
        self.itemLabelTextBrowser_33 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_33.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_33.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_33.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_33.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_33.setObjectName("itemLabelTextBrowser_33")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_33)
        self.itemLabelTextBrowser_34 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_34.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_34.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_34.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_34.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_34.setObjectName("itemLabelTextBrowser_34")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_34)
        self.itemLabelTextBrowser_35 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_35.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_35.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_35.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_35.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_35.setObjectName("itemLabelTextBrowser_35")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_35)
        self.itemLabelTextBrowser_36 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_36.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_36.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_36.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_36.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_36.setObjectName("itemLabelTextBrowser_36")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_36)
        self.itemLabelTextBrowser_37 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_37.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_37.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_37.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_37.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_37.setObjectName("itemLabelTextBrowser_37")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_37)
        self.itemLabelTextBrowser_38 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_38.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_38.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_38.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_38.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_38.setObjectName("itemLabelTextBrowser_38")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_38)
        self.itemLabelTextBrowser_39 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_39.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_39.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_39.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_39.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_39.setObjectName("itemLabelTextBrowser_39")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_39)
        self.itemLabelTextBrowser_40 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemLabelTextBrowser_40.sizePolicy().hasHeightForWidth())
        self.itemLabelTextBrowser_40.setSizePolicy(sizePolicy)
        self.itemLabelTextBrowser_40.setMinimumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_40.setMaximumSize(QtCore.QSize(161, 31))
        self.itemLabelTextBrowser_40.setObjectName("itemLabelTextBrowser_40")
        self.verticalLayout_6.addWidget(self.itemLabelTextBrowser_40)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.itemValueTextBrowser_21 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_21.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_21.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_21.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_21.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_21.setObjectName("itemValueTextBrowser_21")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_21)
        self.itemValueTextBrowser_22 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_22.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_22.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_22.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_22.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_22.setObjectName("itemValueTextBrowser_22")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_22)
        self.itemValueTextBrowser_23 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_23.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_23.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_23.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_23.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_23.setObjectName("itemValueTextBrowser_23")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_23)
        self.itemValueTextBrowser_24 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_24.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_24.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_24.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_24.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_24.setObjectName("itemValueTextBrowser_24")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_24)
        self.itemValueTextBrowser_25 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_25.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_25.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_25.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_25.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_25.setObjectName("itemValueTextBrowser_25")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_25)
        self.itemValueTextBrowser_26 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_26.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_26.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_26.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_26.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_26.setObjectName("itemValueTextBrowser_26")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_26)
        self.itemValueTextBrowser_27 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_27.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_27.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_27.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_27.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_27.setObjectName("itemValueTextBrowser_27")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_27)
        self.itemValueTextBrowser_28 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_28.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_28.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_28.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_28.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_28.setObjectName("itemValueTextBrowser_28")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_28)
        self.itemValueTextBrowser_29 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_29.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_29.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_29.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_29.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_29.setObjectName("itemValueTextBrowser_29")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_29)
        self.itemValueTextBrowser_30 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_30.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_30.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_30.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_30.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_30.setObjectName("itemValueTextBrowser_30")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_30)
        self.itemValueTextBrowser_31 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_31.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_31.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_31.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_31.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_31.setObjectName("itemValueTextBrowser_31")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_31)
        self.itemValueTextBrowser_32 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_32.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_32.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_32.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_32.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_32.setObjectName("itemValueTextBrowser_32")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_32)
        self.itemValueTextBrowser_33 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_33.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_33.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_33.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_33.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_33.setObjectName("itemValueTextBrowser_33")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_33)
        self.itemValueTextBrowser_34 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_34.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_34.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_34.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_34.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_34.setObjectName("itemValueTextBrowser_34")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_34)
        self.itemValueTextBrowser_35 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_35.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_35.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_35.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_35.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_35.setObjectName("itemValueTextBrowser_35")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_35)
        self.itemValueTextBrowser_36 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_36.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_36.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_36.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_36.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_36.setObjectName("itemValueTextBrowser_36")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_36)
        self.itemValueTextBrowser_37 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_37.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_37.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_37.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_37.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_37.setObjectName("itemValueTextBrowser_37")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_37)
        self.itemValueTextBrowser_38 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_38.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_38.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_38.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_38.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_38.setObjectName("itemValueTextBrowser_38")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_38)
        self.itemValueTextBrowser_39 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_39.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_39.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_39.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_39.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_39.setObjectName("itemValueTextBrowser_39")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_39)
        self.itemValueTextBrowser_40 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemValueTextBrowser_40.sizePolicy().hasHeightForWidth())
        self.itemValueTextBrowser_40.setSizePolicy(sizePolicy)
        self.itemValueTextBrowser_40.setMinimumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_40.setMaximumSize(QtCore.QSize(151, 31))
        self.itemValueTextBrowser_40.setObjectName("itemValueTextBrowser_40")
        self.verticalLayout_7.addWidget(self.itemValueTextBrowser_40)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.label_6 = QtWidgets.QLabel(GenericTelemetryDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)

        self.retranslateUi(GenericTelemetryDialog)
        self.buttonBox.accepted.connect(GenericTelemetryDialog.accept)
        self.buttonBox.rejected.connect(GenericTelemetryDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(GenericTelemetryDialog)

    def retranslateUi(self, GenericTelemetryDialog):
        GenericTelemetryDialog.setWindowTitle(_translate("GenericTelemetryDialog", "Telemetry Page", None))
        self.subSystemTelemetryPageLabel.setText(_translate("GenericTelemetryDialog", "Subsystem Telemetry Page", None))
        self.packetIdLabel.setText(_translate("GenericTelemetryDialog", "Packet ID", None))
        self.label_5.setText(_translate("GenericTelemetryDialog", "Sequence Count", None))
        self.label.setText(_translate("GenericTelemetryDialog", "Telemetry Point Label", None))
        self.label_2.setText(_translate("GenericTelemetryDialog", "Telemetry Point Value", None))
        self.label_4.setText(_translate("GenericTelemetryDialog", "Telemetry Point Label", None))
        self.label_3.setText(_translate("GenericTelemetryDialog", "Telemetry Point Value", None))
        self.label_6.setText(_translate("GenericTelemetryDialog", "*No packets? Remember to select the IP address of your spacecraft in the Main Window.", None))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GenericTelemetryDialog = QtWidgets.QDialog()
    ui = Ui_GenericTelemetryDialog()
    ui.setupUi(GenericTelemetryDialog)
    GenericTelemetryDialog.show()
    sys.exit(app.exec_())

