# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CommandSystemDialog.ui'
#
# Created: Fri Jun 19 20:08:08 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)

class Ui_CommandSystemDialog(object):
    def setupUi(self, CommandSystemDialog):
        CommandSystemDialog.setObjectName("CommandSystemDialog")
        CommandSystemDialog.setWindowModality(QtCore.Qt.NonModal)
        CommandSystemDialog.setEnabled(True)
        CommandSystemDialog.resize(709, 581)
        self.verticalLayout = QtWidgets.QVBoxLayout(CommandSystemDialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(CommandSystemDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(CommandSystemDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.buttonBox = QtWidgets.QDialogButtonBox(CommandSystemDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMinimumSize(QtCore.QSize(90, 0))
        self.buttonBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(CommandSystemDialog)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setBaseSize(QtCore.QSize(0, 800))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 668, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(201, 31))
        self.label_3.setMaximumSize(QtCore.QSize(201, 31))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(81, 31))
        self.label_4.setMaximumSize(QtCore.QSize(81, 31))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(81, 31))
        self.label_5.setMaximumSize(QtCore.QSize(81, 31))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem5 = QtWidgets.QSpacerItem(101, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(121, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SubsysBrowser_0 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_0.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_0.setSizePolicy(sizePolicy)
        self.SubsysBrowser_0.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_0.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_0.setObjectName("SubsysBrowser_0")
        self.horizontalLayout_3.addWidget(self.SubsysBrowser_0)
        self.lineEditPktId_0 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_0.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_0.setSizePolicy(sizePolicy)
        self.lineEditPktId_0.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_0.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_0.setObjectName("lineEditPktId_0")
        self.horizontalLayout_3.addWidget(self.lineEditPktId_0)
        self.lineEdit_0 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_0.sizePolicy().hasHeightForWidth())
        self.lineEdit_0.setSizePolicy(sizePolicy)
        self.lineEdit_0.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_0.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_0.setObjectName("lineEdit_0")
        self.horizontalLayout_3.addWidget(self.lineEdit_0)
        self.pushButton_0 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_0.sizePolicy().hasHeightForWidth())
        self.pushButton_0.setSizePolicy(sizePolicy)
        self.pushButton_0.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_0.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_0.setObjectName("pushButton_0")
        self.horizontalLayout_3.addWidget(self.pushButton_0)
        self.quickButton_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_1.sizePolicy().hasHeightForWidth())
        self.quickButton_1.setSizePolicy(sizePolicy)
        self.quickButton_1.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_1.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_1.setText("")
        self.quickButton_1.setObjectName("quickButton_1")
        self.horizontalLayout_3.addWidget(self.quickButton_1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SubsysBrowser_1 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_1.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_1.setSizePolicy(sizePolicy)
        self.SubsysBrowser_1.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_1.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_1.setObjectName("SubsysBrowser_1")
        self.horizontalLayout_4.addWidget(self.SubsysBrowser_1)
        self.lineEditPktId_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_1.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_1.setSizePolicy(sizePolicy)
        self.lineEditPktId_1.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_1.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_1.setObjectName("lineEditPktId_1")
        self.horizontalLayout_4.addWidget(self.lineEditPktId_1)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_1.setSizePolicy(sizePolicy)
        self.lineEdit_1.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_1.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalLayout_4.addWidget(self.lineEdit_1)
        self.pushButton_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_1.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_4.addWidget(self.pushButton_1)
        self.quickButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_2.sizePolicy().hasHeightForWidth())
        self.quickButton_2.setSizePolicy(sizePolicy)
        self.quickButton_2.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_2.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_2.setText("")
        self.quickButton_2.setObjectName("quickButton_2")
        self.horizontalLayout_4.addWidget(self.quickButton_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.SubsysBrowser_2 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_2.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_2.setSizePolicy(sizePolicy)
        self.SubsysBrowser_2.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_2.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_2.setObjectName("SubsysBrowser_2")
        self.horizontalLayout_5.addWidget(self.SubsysBrowser_2)
        self.lineEditPktId_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_2.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_2.setSizePolicy(sizePolicy)
        self.lineEditPktId_2.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_2.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_2.setObjectName("lineEditPktId_2")
        self.horizontalLayout_5.addWidget(self.lineEditPktId_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_2.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.quickButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_3.sizePolicy().hasHeightForWidth())
        self.quickButton_3.setSizePolicy(sizePolicy)
        self.quickButton_3.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_3.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_3.setText("")
        self.quickButton_3.setObjectName("quickButton_3")
        self.horizontalLayout_5.addWidget(self.quickButton_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.SubsysBrowser_3 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_3.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_3.setSizePolicy(sizePolicy)
        self.SubsysBrowser_3.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_3.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_3.setObjectName("SubsysBrowser_3")
        self.horizontalLayout_7.addWidget(self.SubsysBrowser_3)
        self.lineEditPktId_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_3.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_3.setSizePolicy(sizePolicy)
        self.lineEditPktId_3.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_3.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_3.setObjectName("lineEditPktId_3")
        self.horizontalLayout_7.addWidget(self.lineEditPktId_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_7.addWidget(self.lineEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_3.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        self.quickButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_4.sizePolicy().hasHeightForWidth())
        self.quickButton_4.setSizePolicy(sizePolicy)
        self.quickButton_4.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_4.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_4.setText("")
        self.quickButton_4.setObjectName("quickButton_4")
        self.horizontalLayout_7.addWidget(self.quickButton_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.SubsysBrowser_4 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_4.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_4.setSizePolicy(sizePolicy)
        self.SubsysBrowser_4.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_4.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_4.setObjectName("SubsysBrowser_4")
        self.horizontalLayout_8.addWidget(self.SubsysBrowser_4)
        self.lineEditPktId_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_4.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_4.setSizePolicy(sizePolicy)
        self.lineEditPktId_4.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_4.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_4.setObjectName("lineEditPktId_4")
        self.horizontalLayout_8.addWidget(self.lineEditPktId_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_8.addWidget(self.lineEdit_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_4.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_8.addWidget(self.pushButton_4)
        self.quickButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_5.sizePolicy().hasHeightForWidth())
        self.quickButton_5.setSizePolicy(sizePolicy)
        self.quickButton_5.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_5.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_5.setText("")
        self.quickButton_5.setObjectName("quickButton_5")
        self.horizontalLayout_8.addWidget(self.quickButton_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.SubsysBrowser_5 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_5.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_5.setSizePolicy(sizePolicy)
        self.SubsysBrowser_5.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_5.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_5.setObjectName("SubsysBrowser_5")
        self.horizontalLayout_9.addWidget(self.SubsysBrowser_5)
        self.lineEditPktId_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_5.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_5.setSizePolicy(sizePolicy)
        self.lineEditPktId_5.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_5.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_5.setObjectName("lineEditPktId_5")
        self.horizontalLayout_9.addWidget(self.lineEditPktId_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_9.addWidget(self.lineEdit_5)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_5.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_9.addWidget(self.pushButton_5)
        self.quickButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_6.sizePolicy().hasHeightForWidth())
        self.quickButton_6.setSizePolicy(sizePolicy)
        self.quickButton_6.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_6.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_6.setText("")
        self.quickButton_6.setObjectName("quickButton_6")
        self.horizontalLayout_9.addWidget(self.quickButton_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.SubsysBrowser_6 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_6.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_6.setSizePolicy(sizePolicy)
        self.SubsysBrowser_6.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_6.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_6.setObjectName("SubsysBrowser_6")
        self.horizontalLayout_10.addWidget(self.SubsysBrowser_6)
        self.lineEditPktId_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_6.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_6.setSizePolicy(sizePolicy)
        self.lineEditPktId_6.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_6.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_6.setObjectName("lineEditPktId_6")
        self.horizontalLayout_10.addWidget(self.lineEditPktId_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_10.addWidget(self.lineEdit_6)
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_6.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_10.addWidget(self.pushButton_6)
        self.quickButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_7.sizePolicy().hasHeightForWidth())
        self.quickButton_7.setSizePolicy(sizePolicy)
        self.quickButton_7.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_7.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_7.setText("")
        self.quickButton_7.setObjectName("quickButton_7")
        self.horizontalLayout_10.addWidget(self.quickButton_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.SubsysBrowser_7 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_7.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_7.setSizePolicy(sizePolicy)
        self.SubsysBrowser_7.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_7.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_7.setObjectName("SubsysBrowser_7")
        self.horizontalLayout_11.addWidget(self.SubsysBrowser_7)
        self.lineEditPktId_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_7.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_7.setSizePolicy(sizePolicy)
        self.lineEditPktId_7.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_7.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_7.setObjectName("lineEditPktId_7")
        self.horizontalLayout_11.addWidget(self.lineEditPktId_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_11.addWidget(self.lineEdit_7)
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_7.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_11.addWidget(self.pushButton_7)
        self.quickButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_8.sizePolicy().hasHeightForWidth())
        self.quickButton_8.setSizePolicy(sizePolicy)
        self.quickButton_8.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_8.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_8.setText("")
        self.quickButton_8.setObjectName("quickButton_8")
        self.horizontalLayout_11.addWidget(self.quickButton_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.SubsysBrowser_8 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_8.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_8.setSizePolicy(sizePolicy)
        self.SubsysBrowser_8.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_8.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_8.setObjectName("SubsysBrowser_8")
        self.horizontalLayout_12.addWidget(self.SubsysBrowser_8)
        self.lineEditPktId_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_8.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_8.setSizePolicy(sizePolicy)
        self.lineEditPktId_8.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_8.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_8.setObjectName("lineEditPktId_8")
        self.horizontalLayout_12.addWidget(self.lineEditPktId_8)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_12.addWidget(self.lineEdit_8)
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_8.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_12.addWidget(self.pushButton_8)
        self.quickButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_9.sizePolicy().hasHeightForWidth())
        self.quickButton_9.setSizePolicy(sizePolicy)
        self.quickButton_9.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_9.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_9.setText("")
        self.quickButton_9.setObjectName("quickButton_9")
        self.horizontalLayout_12.addWidget(self.quickButton_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.SubsysBrowser_9 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_9.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_9.setSizePolicy(sizePolicy)
        self.SubsysBrowser_9.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_9.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_9.setObjectName("SubsysBrowser_9")
        self.horizontalLayout_13.addWidget(self.SubsysBrowser_9)
        self.lineEditPktId_9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_9.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_9.setSizePolicy(sizePolicy)
        self.lineEditPktId_9.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_9.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_9.setObjectName("lineEditPktId_9")
        self.horizontalLayout_13.addWidget(self.lineEditPktId_9)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_13.addWidget(self.lineEdit_9)
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_9.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_13.addWidget(self.pushButton_9)
        self.quickButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_10.sizePolicy().hasHeightForWidth())
        self.quickButton_10.setSizePolicy(sizePolicy)
        self.quickButton_10.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_10.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_10.setText("")
        self.quickButton_10.setObjectName("quickButton_10")
        self.horizontalLayout_13.addWidget(self.quickButton_10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.SubsysBrowser_10 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_10.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_10.setSizePolicy(sizePolicy)
        self.SubsysBrowser_10.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_10.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_10.setObjectName("SubsysBrowser_10")
        self.horizontalLayout_14.addWidget(self.SubsysBrowser_10)
        self.lineEditPktId_10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_10.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_10.setSizePolicy(sizePolicy)
        self.lineEditPktId_10.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_10.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_10.setObjectName("lineEditPktId_10")
        self.horizontalLayout_14.addWidget(self.lineEditPktId_10)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_14.addWidget(self.lineEdit_10)
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_10.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_14.addWidget(self.pushButton_10)
        self.quickButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_11.sizePolicy().hasHeightForWidth())
        self.quickButton_11.setSizePolicy(sizePolicy)
        self.quickButton_11.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_11.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_11.setText("")
        self.quickButton_11.setObjectName("quickButton_11")
        self.horizontalLayout_14.addWidget(self.quickButton_11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.SubsysBrowser_11 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_11.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_11.setSizePolicy(sizePolicy)
        self.SubsysBrowser_11.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_11.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_11.setObjectName("SubsysBrowser_11")
        self.horizontalLayout_15.addWidget(self.SubsysBrowser_11)
        self.lineEditPktId_11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_11.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_11.setSizePolicy(sizePolicy)
        self.lineEditPktId_11.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_11.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_11.setObjectName("lineEditPktId_11")
        self.horizontalLayout_15.addWidget(self.lineEditPktId_11)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_15.addWidget(self.lineEdit_11)
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_11.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_15.addWidget(self.pushButton_11)
        self.quickButton_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_12.sizePolicy().hasHeightForWidth())
        self.quickButton_12.setSizePolicy(sizePolicy)
        self.quickButton_12.setMinimumSize(QtCore.QSize(121, 0))
        self.quickButton_12.setMaximumSize(QtCore.QSize(121, 16777215))
        self.quickButton_12.setText("")
        self.quickButton_12.setObjectName("quickButton_12")
        self.horizontalLayout_15.addWidget(self.quickButton_12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.SubsysBrowser_12 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_12.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_12.setSizePolicy(sizePolicy)
        self.SubsysBrowser_12.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_12.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_12.setObjectName("SubsysBrowser_12")
        self.horizontalLayout_16.addWidget(self.SubsysBrowser_12)
        self.lineEditPktId_12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_12.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_12.setSizePolicy(sizePolicy)
        self.lineEditPktId_12.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_12.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_12.setObjectName("lineEditPktId_12")
        self.horizontalLayout_16.addWidget(self.lineEditPktId_12)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_12.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_16.addWidget(self.lineEdit_12)
        self.pushButton_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_12.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_16.addWidget(self.pushButton_12)
        self.quickButton_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_13.sizePolicy().hasHeightForWidth())
        self.quickButton_13.setSizePolicy(sizePolicy)
        self.quickButton_13.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_13.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_13.setText("")
        self.quickButton_13.setObjectName("quickButton_13")
        self.horizontalLayout_16.addWidget(self.quickButton_13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.SubsysBrowser_13 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_13.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_13.setSizePolicy(sizePolicy)
        self.SubsysBrowser_13.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_13.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_13.setObjectName("SubsysBrowser_13")
        self.horizontalLayout_17.addWidget(self.SubsysBrowser_13)
        self.lineEditPktId_13 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_13.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_13.setSizePolicy(sizePolicy)
        self.lineEditPktId_13.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_13.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_13.setObjectName("lineEditPktId_13")
        self.horizontalLayout_17.addWidget(self.lineEditPktId_13)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_13.sizePolicy().hasHeightForWidth())
        self.lineEdit_13.setSizePolicy(sizePolicy)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_13.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_17.addWidget(self.lineEdit_13)
        self.pushButton_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_13.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_17.addWidget(self.pushButton_13)
        self.quickButton_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_14.sizePolicy().hasHeightForWidth())
        self.quickButton_14.setSizePolicy(sizePolicy)
        self.quickButton_14.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_14.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_14.setText("")
        self.quickButton_14.setObjectName("quickButton_14")
        self.horizontalLayout_17.addWidget(self.quickButton_14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.SubsysBrowser_14 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_14.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_14.setSizePolicy(sizePolicy)
        self.SubsysBrowser_14.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_14.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_14.setObjectName("SubsysBrowser_14")
        self.horizontalLayout_18.addWidget(self.SubsysBrowser_14)
        self.lineEditPktId_14 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_14.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_14.setSizePolicy(sizePolicy)
        self.lineEditPktId_14.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_14.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_14.setObjectName("lineEditPktId_14")
        self.horizontalLayout_18.addWidget(self.lineEditPktId_14)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_14.sizePolicy().hasHeightForWidth())
        self.lineEdit_14.setSizePolicy(sizePolicy)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_14.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_18.addWidget(self.lineEdit_14)
        self.pushButton_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_14.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_18.addWidget(self.pushButton_14)
        self.quickButton_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_15.sizePolicy().hasHeightForWidth())
        self.quickButton_15.setSizePolicy(sizePolicy)
        self.quickButton_15.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_15.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_15.setText("")
        self.quickButton_15.setObjectName("quickButton_15")
        self.horizontalLayout_18.addWidget(self.quickButton_15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.SubsysBrowser_15 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_15.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_15.setSizePolicy(sizePolicy)
        self.SubsysBrowser_15.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_15.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_15.setObjectName("SubsysBrowser_15")
        self.horizontalLayout_19.addWidget(self.SubsysBrowser_15)
        self.lineEditPktId_15 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_15.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_15.setSizePolicy(sizePolicy)
        self.lineEditPktId_15.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_15.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_15.setObjectName("lineEditPktId_15")
        self.horizontalLayout_19.addWidget(self.lineEditPktId_15)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_15.sizePolicy().hasHeightForWidth())
        self.lineEdit_15.setSizePolicy(sizePolicy)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_15.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_19.addWidget(self.lineEdit_15)
        self.pushButton_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_15.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_19.addWidget(self.pushButton_15)
        self.quickButton_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_16.sizePolicy().hasHeightForWidth())
        self.quickButton_16.setSizePolicy(sizePolicy)
        self.quickButton_16.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_16.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_16.setText("")
        self.quickButton_16.setObjectName("quickButton_16")
        self.horizontalLayout_19.addWidget(self.quickButton_16)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.SubsysBrowser_16 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_16.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_16.setSizePolicy(sizePolicy)
        self.SubsysBrowser_16.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_16.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_16.setObjectName("SubsysBrowser_16")
        self.horizontalLayout_20.addWidget(self.SubsysBrowser_16)
        self.lineEditPktId_16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_16.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_16.setSizePolicy(sizePolicy)
        self.lineEditPktId_16.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_16.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_16.setObjectName("lineEditPktId_16")
        self.horizontalLayout_20.addWidget(self.lineEditPktId_16)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_16.sizePolicy().hasHeightForWidth())
        self.lineEdit_16.setSizePolicy(sizePolicy)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_16.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_20.addWidget(self.lineEdit_16)
        self.pushButton_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_16.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_20.addWidget(self.pushButton_16)
        self.quickButton_17 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_17.sizePolicy().hasHeightForWidth())
        self.quickButton_17.setSizePolicy(sizePolicy)
        self.quickButton_17.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_17.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_17.setText("")
        self.quickButton_17.setObjectName("quickButton_17")
        self.horizontalLayout_20.addWidget(self.quickButton_17)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.SubsysBrowser_17 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_17.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_17.setSizePolicy(sizePolicy)
        self.SubsysBrowser_17.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_17.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_17.setObjectName("SubsysBrowser_17")
        self.horizontalLayout_21.addWidget(self.SubsysBrowser_17)
        self.lineEditPktId_17 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_17.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_17.setSizePolicy(sizePolicy)
        self.lineEditPktId_17.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_17.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_17.setObjectName("lineEditPktId_17")
        self.horizontalLayout_21.addWidget(self.lineEditPktId_17)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_17.sizePolicy().hasHeightForWidth())
        self.lineEdit_17.setSizePolicy(sizePolicy)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_17.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_21.addWidget(self.lineEdit_17)
        self.pushButton_17 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_17.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_21.addWidget(self.pushButton_17)
        self.quickButton_18 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_18.sizePolicy().hasHeightForWidth())
        self.quickButton_18.setSizePolicy(sizePolicy)
        self.quickButton_18.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_18.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_18.setText("")
        self.quickButton_18.setObjectName("quickButton_18")
        self.horizontalLayout_21.addWidget(self.quickButton_18)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.SubsysBrowser_18 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_18.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_18.setSizePolicy(sizePolicy)
        self.SubsysBrowser_18.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_18.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_18.setObjectName("SubsysBrowser_18")
        self.horizontalLayout_22.addWidget(self.SubsysBrowser_18)
        self.lineEditPktId_18 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_18.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_18.setSizePolicy(sizePolicy)
        self.lineEditPktId_18.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_18.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_18.setObjectName("lineEditPktId_18")
        self.horizontalLayout_22.addWidget(self.lineEditPktId_18)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_18.sizePolicy().hasHeightForWidth())
        self.lineEdit_18.setSizePolicy(sizePolicy)
        self.lineEdit_18.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_18.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_22.addWidget(self.lineEdit_18)
        self.pushButton_18 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_18.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_22.addWidget(self.pushButton_18)
        self.quickButton_19 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_19.sizePolicy().hasHeightForWidth())
        self.quickButton_19.setSizePolicy(sizePolicy)
        self.quickButton_19.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_19.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_19.setText("")
        self.quickButton_19.setObjectName("quickButton_19")
        self.horizontalLayout_22.addWidget(self.quickButton_19)
        self.verticalLayout_4.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.SubsysBrowser_19 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_19.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_19.setSizePolicy(sizePolicy)
        self.SubsysBrowser_19.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_19.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_19.setObjectName("SubsysBrowser_19")
        self.horizontalLayout_23.addWidget(self.SubsysBrowser_19)
        self.lineEditPktId_19 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_19.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_19.setSizePolicy(sizePolicy)
        self.lineEditPktId_19.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_19.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_19.setObjectName("lineEditPktId_19")
        self.horizontalLayout_23.addWidget(self.lineEditPktId_19)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_19.sizePolicy().hasHeightForWidth())
        self.lineEdit_19.setSizePolicy(sizePolicy)
        self.lineEdit_19.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_19.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_23.addWidget(self.lineEdit_19)
        self.pushButton_19 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_19.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_19.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_23.addWidget(self.pushButton_19)
        self.quickButton_20 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_20.sizePolicy().hasHeightForWidth())
        self.quickButton_20.setSizePolicy(sizePolicy)
        self.quickButton_20.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_20.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_20.setText("")
        self.quickButton_20.setObjectName("quickButton_20")
        self.horizontalLayout_23.addWidget(self.quickButton_20)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.SubsysBrowser_20 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_20.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_20.setSizePolicy(sizePolicy)
        self.SubsysBrowser_20.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_20.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_20.setObjectName("SubsysBrowser_20")
        self.horizontalLayout_24.addWidget(self.SubsysBrowser_20)
        self.lineEditPktId_20 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_20.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_20.setSizePolicy(sizePolicy)
        self.lineEditPktId_20.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_20.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_20.setObjectName("lineEditPktId_20")
        self.horizontalLayout_24.addWidget(self.lineEditPktId_20)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_20.sizePolicy().hasHeightForWidth())
        self.lineEdit_20.setSizePolicy(sizePolicy)
        self.lineEdit_20.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_20.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_24.addWidget(self.lineEdit_20)
        self.pushButton_20 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_20.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_20.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_24.addWidget(self.pushButton_20)
        self.quickButton_21 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_21.sizePolicy().hasHeightForWidth())
        self.quickButton_21.setSizePolicy(sizePolicy)
        self.quickButton_21.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_21.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_21.setText("")
        self.quickButton_21.setObjectName("quickButton_21")
        self.horizontalLayout_24.addWidget(self.quickButton_21)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.SubsysBrowser_21 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubsysBrowser_21.sizePolicy().hasHeightForWidth())
        self.SubsysBrowser_21.setSizePolicy(sizePolicy)
        self.SubsysBrowser_21.setMinimumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_21.setMaximumSize(QtCore.QSize(201, 31))
        self.SubsysBrowser_21.setObjectName("SubsysBrowser_21")
        self.horizontalLayout_25.addWidget(self.SubsysBrowser_21)
        self.lineEditPktId_21 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPktId_21.sizePolicy().hasHeightForWidth())
        self.lineEditPktId_21.setSizePolicy(sizePolicy)
        self.lineEditPktId_21.setMinimumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_21.setMaximumSize(QtCore.QSize(81, 31))
        self.lineEditPktId_21.setObjectName("lineEditPktId_21")
        self.horizontalLayout_25.addWidget(self.lineEditPktId_21)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_21.sizePolicy().hasHeightForWidth())
        self.lineEdit_21.setSizePolicy(sizePolicy)
        self.lineEdit_21.setMinimumSize(QtCore.QSize(100, 31))
        self.lineEdit_21.setMaximumSize(QtCore.QSize(100, 31))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_25.addWidget(self.lineEdit_21)
        self.pushButton_21 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton_21.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton_21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_25.addWidget(self.pushButton_21)
        self.quickButton_22 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickButton_22.sizePolicy().hasHeightForWidth())
        self.quickButton_22.setSizePolicy(sizePolicy)
        self.quickButton_22.setMinimumSize(QtCore.QSize(121, 32))
        self.quickButton_22.setMaximumSize(QtCore.QSize(121, 32))
        self.quickButton_22.setText("")
        self.quickButton_22.setObjectName("quickButton_22")
        self.horizontalLayout_25.addWidget(self.quickButton_22)
        self.verticalLayout_4.addLayout(self.horizontalLayout_25)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(CommandSystemDialog)
        self.buttonBox.clicked[QAbstractButton].connect(CommandSystemDialog.close)
        QtCore.QMetaObject.connectSlotsByName(CommandSystemDialog)

    def retranslateUi(self, CommandSystemDialog):
        CommandSystemDialog.setWindowTitle(_translate("CommandSystemDialog", "Command System", None))
        self.label.setText(_translate("CommandSystemDialog", "cFE/CFS Subsystem Commands", None))
        self.label_2.setText(_translate("CommandSystemDialog", "Available Pages", None))
        self.label_3.setText(_translate("CommandSystemDialog", "Subsystem/Page", None))
        self.label_4.setText(_translate("CommandSystemDialog", "Packet ID", None))
        self.label_5.setText(_translate("CommandSystemDialog", "Send To", None))
        self.pushButton_0.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_1.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_2.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_3.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_4.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_5.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_6.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_7.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_8.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_9.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_10.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_11.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_12.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_13.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_14.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_15.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_16.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_17.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_18.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_19.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_20.setText(_translate("CommandSystemDialog", "Display Page", None))
        self.pushButton_21.setText(_translate("CommandSystemDialog", "Display Page", None))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CommandSystemDialog = QtWidgets.QWidget()
    ui = Ui_CommandSystemDialog()
    ui.setupUi(CommandSystemDialog)
    CommandSystemDialog.show()
    sys.exit(app.exec_())

